### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by sugo23** [xenforo-ltd/docs#13]
on [https://xf2demo.xenforo.com/dev-docs/entities-finders-repositories/#the-entity-life-cycle](url)

> Repositories are a new concept for XF2, but you might not be blamed for comparing them to the "Model" objects from XF1. We don't have a model object in XF1 because we have much better places and ways to fetch and write data to the database. So, rather than having a massive class which contains all of the queries your add-on needs, and all of the various different ways to manipulate those queries, we have the finder which adds a lot more flexibility.

Shouldn't it say "XF2" in the second sentence?

**Comment by chrisdeeming** [comment]
Sorted thanks :)
