### ISSUE TITLE
Adding multiple phrases

### ISSUE THREAD

**Issue by Myke623** [xenforo-ltd/docs#28]
In section **Manually featuring (or unfeaturing) threads**, the paragraph describing the phrase additions:

> Under "Appearance" go to "Phrases" and click "Add phrase". Make sure your add-on is selected. The "Title" of the first phrase will be "demo_portal_featured" and the text will be simply "Featured". Click "Save". Click "Add phrase" again. The "Title" for the second phrase will be "demo_portal_featured_hint" and the text will be "Featured threads will appear on the Portal page."

When you click "Save" on the first phrase you're not redirected back to the Phrases page and as result, there's no option to "Add phrase" again. So instead of clicking "Save", click on "Save and Exit".

**Comment by SamJakob** [comment]
Updated in my branch so I'll submit this with my pull request.
