### ISSUE TITLE
Tips on schema declaration when adding to database tables

### ISSUE THREAD

**Issue by belazor** [xenforo-ltd/docs#29]
See this thread: https://xenforo.com/community/threads/nf_discord_enable-doesnt-have-a-default-value-if-i-create-a-node.137996/#post-1195602

It would be helpful if the docs mentioned somewhere that when extending default XF tables, or the tables of another add-on, your columns MUST specify a default value, otherwise these issues occur.

Also, adding the line somewhere about using vendor prefixes when extending XF tables.

**Comment by SamJakob** [comment]
I've resolved this in my own fork so I'll submit this with my pull request.

**Comment by SamJakob** [comment]
@chrisdeeming This one wasn't closed.
