### ISSUE TITLE
"Bump your add-on version" - mention needing quotes if version string contains spaces

### ISSUE THREAD

**Issue by belazor** [xenforo-ltd/docs#30]
`xf-addon:bump-version DBTech/Credits --version-id 905000032 --version-string 5.0.0 Beta 2`
= Too many arguments, expected arguments "command" "id".

` xf-addon:bump-version DBTech/Credits --version-id=905000032 --version-string="5.0.0 Beta 2"`
= works

I didn't test it without the = signs, though.

**Comment by SamJakob** [comment]
I can confirm it works without the = signs.
Updated in my branch so I'll submit this with my pull request.
