### ISSUE TITLE
Link in docs throws a 404

### ISSUE THREAD

**Issue by mbooth** [xenforo-ltd/docs#42]
There is an incorrect URL located at
https://xenforo.com/xf2-docs/dev/lets-build-an-add-on/#create-the-add-on

This text "Managing the Schema section" links to : 
https://xenforo.com/xf2-docs/managing-the-schema/
When it should be:
https://xenforo.com/xf2-docs/dev/managing-the-schema/

**Comment by SamJakob** [comment]
This issue has been fixed and can be closed.
