### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by AJerm** [xenforo-ltd/docs#52]
In https://xenforo.com/docs/dev/routing-basics/

The following links are broken:

https://xenforo.com/general-concepts/#short-class-names
https://xenforo.com/controller-basics

**Comment by AJerm** [comment]
Also here

https://xenforo.com/docs/dev/general-concepts/

In extending classes section, where linking to the xf-addon:create page

https://xenforo.com/development-tools/#creating-a-new-add-on

**Comment by AJerm** [comment]
Also the controller basics link on the same page

https://xenforo.com/controller-basics

**Comment by AJerm** [comment]
And the modifying a controller action reply (properly) link on the same page

https://xenforo.com/controller-basics/#modifying-a-controller-action-reply-properly

**Comment by chrisdeeming** [comment]
These issues (and others) should be resolved now. Thanks!
