### ISSUE TITLE
->limitByPage($page, $perPage * 3) does not work with pagination

### ISSUE THREAD

**Issue by sugo23** [xenforo-ltd/docs#9]
When i follow these steps:

[https://xf2demo.xenforo.com/dev-docs/lets-build-an-add-on/#implementing-permissions-optimizations](url)

Especially this instruction:

> To start, go to the Portal controller, and change this line:
> `->limitByPage($page, $perPage);`
> To:
> `->limitByPage($page, $perPage * 3);`

Then page 2 does not show any threads anymore. If I leave the `* 3` away, then it works as expected

**Comment by chrisdeeming** [comment]
Appreciate the bug reports in the documentation. I'm not certain this is a bug in the documentation, though. Support with development in general should be done at https://xf2demo.xenforo.com.
